= telegram-kafka project
A Camel Quarkus example with Telegram / Kafka / AWS S3 / Google Sheets

An example that shows how to create a Telegram bot using camel-quarkus, and how to produce and consume messages in a Kafka topic, and in postgesql database. It also shows how to set quickly a REST endpoint using platform-http. It also shows some implementations of Content Based Router EIP and Message Translator EIP.

==== Prerequisites

The example application requires an existing Telegram bot, a running Kafka instance, and a S3 bucket instance.
For simplicity, on dev mode : this example uses quarkus DevServices to launch a kafka instance, and localstack to emulate S3.

==== Start S3 locally

Start an  instance of localstack
----
$ cd setup
$ docker-compose up
----

Then open another terminal to create a bucket
IMPORTANT: you will need the AWS cli installed, to execute this command
----
$ aws --endpoint-url=http://localhost:4566 s3 mb s3://test1
----

==== Start in Development mode

Set your telegram Token:
----
$ export TELEGRAM_AUTHORIZATION_TOKEN=INSERT_YOUR_TELEGRAM_AUTHORIZATION_TOKEN
----

Run the application in development mode.

----
$ mvn clean compile quarkus:dev
----

=== Package and run the application locally

Once you are done with developing you may want to package and run the application. You need to export KAFKA and AWS S3 credentials:

----
$ export KAFKA_BOOSTRAP_URL=INSERT_HERE_YOUR_BOOSTRAP_URL
$ export AWS_S3_BUCKET_NAME=INSERT_HERE_YOUR_AWS_S3_BUCKET_NAME
$ export AWS_ACCESS_KEY=INSERT_HERE_YOUR_AWS_ACCESS_KEY_ID
$ export AWS_SECRET_KEY=INSERT_HERE_YOUR_AWS_SECRET_KEY
$ export AWS_REGION=INSERT_HERE_YOUR_AWS_REGION
----

IMPORTANT: If you don't have any instances of Kafka and S3, go to section Install Kafka and S3 locally

==== JVM mode

----
$ mvn clean package -DskipTests
$ java -jar target/quarkus-app/quarkus-run.jar
----

==== Native mode

IMPORTANT: Native mode requires having GraalVM and other tools installed. Please check the Prerequisites section
of https://camel.apache.org/camel-quarkus/latest/first-steps.html#_prerequisites[Camel Quarkus User guide].

To prepare a native executable using GraalVM, run the following command:

----
$ mvn clean package -DskipTests -Pnative
$ ./target/*-runner
----

==== Deploying to Kubernetes

You can build a container image for the application like this. Refer to the https://quarkus.io/guides/deploying-to-kubernetes[Quarkus Kubernetes guide] for options around customizing image names, registries etc.

Uncomment the container build section. Set the proper image group.

----
$ mvn clean package -DskipTests
----

If you are using a local development cluster like Kind or k3s, you can use host the container image on your local host. Or, with minikube, use the Docker daemon from the cluster virtual machine `eval $(minikube docker-env)`. Otherwise, you'll need to push the image to a registry of your choosing.

TIP: You can build &amp; deploy in one single step by doing `mvn clean package -DskipTests -Dquarkus.kubernetes.deploy=true`

Check pods are running.

Tail the application logs.
----
$ kubectl logs -f  telegram-kafka-67ddc468d-z9kzt
----
To clean up do.
----
$ kubectl delete all -l app.kubernetes.io/name=telegram-kafkan
----
==== Deploying to OpenShift
You may need to set the credentials in `src/main/resources/applications.properties` or attach a kubernetes secrect.
----
$ mvn clean package -DskipTests -Dquarkus.kubernetes.deploy=true -Dopenshift
----

==== Install Kafka and S3 locally

Install Kafka using this command line
----
$ docker run -d --name=redpanda-1 --rm \
        -p 9092:9092 \
        -p 9644:9644 \
        docker.vectorized.io/vectorized/redpanda:v22.1.2 \
        redpanda start \
        --overprovisioned \
            --smp 1  \
            --memory 1G \
            --reserve-memory 0M \
            --node-id 0 \
            --check=false
----

Create a topic
----
    docker exec -it redpanda-1 \
        rpk topic create telegram-message --brokers=localhost:9092
----

Export Kafka URL broker
----
$ export KAFKA_BOOSTRAP_URL=127.0.0.1:9092
----

Start an  instance of localstack
----
$ cd setup
$ docker-compose up
----

Then open another terminal to create a bucket
IMPORTANT: you will need the AWS cli installed, to execute this command
----
$ aws --endpoint-url=http://localhost:4566 s3 mb s3://test1
----

update application.properties with those values

----
camel.component.aws2-s3.override-endpoint=true
camel.component.aws2-s3.uri-endpoint-override=http://localhost:4566
----

At the end of tests, stop instances
----
$ docker stop redpanda-1
----

=== Google OAuth2

* Create a new OAuth app on https://developers.google.com/identity/protocols/oauth2
* Allow access to https://www.googleapis.com/auth/spreadsheets
* You should get `credentials.json` similar to the following:
+
[source,json]
----
{
"web":{
  "client_id":"1234abcd.apps.googleusercontent.com",
  "project_id":"my-app-name",
  "auth_uri":"https://accounts.google.com/o/oauth2/auth",
  "token_uri":"https://oauth2.googleapis.com/token",
  "auth_provider_x509_cert_url":"https://www.googleapis.com/oauth2/v1/certs",
  "client_secret":"ABCDE-ABCD1234",
  "redirect_uris":["http://localhost:8080"]}
}
----
+
* Based on the above values construct an URL and visit it in the browser:
+
[source,shell]
----
https://accounts.google.com/o/oauth2/v2/auth?client_id=1234abcd.apps.googleusercontent.com&redirect_uri=http://localhost:8080&scope=https://www.googleapis.com/auth/spreadsheets&response_type=code&prompt=consent&access_type=offline
----
+
* It should return a redirect like `http://localhost:8080?code=4/ABCD1234-abcd1234_abcd`
* Take that `code` URL parameter and send the following POST request using curl:
+
[source,shell]
----
curl -s \
 --request POST \
 --data "code=4/ABCD1234-abcd1234_abcd&client_id=1234abcd.apps.googleusercontent.com&client_secret=ABCDE-ABCD1234&redirect_uri=http://localhost:8080&grant_type=authorization_code" \
 https://accounts.google.com/o/oauth2/token
{
  "access_token": "abcdEFGH",
  "expires_in": 3599,
  "refresh_token": "1//abcdEFGH",
  "scope": "https://www.googleapis.com/auth/spreadsheets",
  "token_type": "Bearer"
}
----
* Have the Google credentials in your environment:
+
[source,shell]
----
export GOOGLE_API_APPLICATION_NAME=...
export GOOGLE_API_CLIENT_ID=...
export GOOGLE_API_CLIENT_SECRET=...
export GOOGLE_API_REFRESH_TOKEN=...
# Take the spreadsheetId from the given spredsheet's URL
# https://docs.google.com/spreadsheets/d/{spreadsheetId}/edit#gid=0
export GOOGLE_API_SPREADSHEET_ID=...
----

