apiVersion: camel.apache.org/v1alpha1
kind: KameletBinding
metadata:
  name: chuck-norris-source
spec:
  source:
    ref:
      kind: Kamelet
      apiVersion: camel.apache.org/v1alpha1
      name: chuck-norris-source
  sink:
    ref:
      kind: Channel
      apiVersion: messaging.knative.dev/v1
      name: jokes