= Camel K demo

== Prerequisites & preparations

* A Kubernetes or OpenShift cluster with permissions to install operators.

=== Preparations in the cluster

=== For OpenShift

* `oc new-project camel-k-demo`
* Install RH Serverless (a.k.a. Knative) Operator
* Install Camel K Operator

=== For Minikube

* https://redhat-developer-demos.github.io/knative-tutorial/knative-tutorial/setup/minikube.html[Install Knative]
* https://camel.apache.org/camel-k/latest/installation/installation.html[Install Camel K] via `kamel install`

=== S3

* Have S3 credentials ready in the shell
* These are the same as you have used for the Camel Quarkus demo in the parent directory
* Note that the bucket must exist before running this demo, and it should contain some messages delivered by
  the Camel Quarkus demo.
* You even may keep the Quarkus app running in dev mode and see the messages arriving in the spreadsheet
+
[source,shell]
----
export AWS_ACCESS_KEY=...
export AWS_SECRET_KEY=...
export AWS_REGION=...
export AWS_S3_BUCKET_NAME=...
----

=== Create the secrets

Now you have all pieces to create the secrets for the two integrations.
These steps are for OpenShift.
For Kubernetes, just replace `oc` with `kubectl`

[source,shell]
----
oc login ...
oc new-project camel-k-demo
# For Kubernetes:
# kubectl create namespace camel-k-demo
# kubectl config set-context --current --namespace=camel-k-demo

# Make sure the secrets do not exist yet
oc delete secret s3-secret
mkdir -p target
cat s3.properties | envsubst > target/application.properties
oc create secret generic s3-secret --from-file=target/application.properties
rm target/application.properties
----



== Create the Knative channel

----
$ oc apply -f jokes-channel.yaml
----

== Deploy the routes

[source,shell]
----
$ kubectl label secret s3-secret camel.apache.org/kamelet=aws-s3-sink
$ kubectl apply -f chuck-norris.yaml
$ kubectl apply -f S3ToKnative.groovy
----
